# TODO: remove this once we're no longer compiling C++ with Rust.
[future-incompat-report]
frequency = "never"

[alias]
bin = ["run", "--quiet", "--package", "cargo-bin", "--"]
binstall = ["bin", "cargo-binstall"]
