name: CI

on: [push, pull_request]

jobs:
  cpp:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: ./build/bin/twsearch -g samples/main/2x2x2.tws
      - run: make test-cpp-cli

  cpp-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: make
      - uses: actions/upload-artifact@v4
        with:
          name: twsearch-cpp-windows
          path: build/bin/

  cpp-wrapper-cli:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: make test-twsearch-cpp-wrapper-cli

  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: make build-rust
      - run: make test-rust-lib
      - run: make test-rust-examples
      - run: make lint-rust
      - run: make benchmark-rust

  rust-ffi:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: cargo bin --install
      - run: make build-rust-ffi
      - run: make test-rust-ffi

  rust-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use `node` v19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v4
        with:
          path: .bin
          key: ${{ runner.os }}-cargo-run-bin
      - run: cargo bin --install
      - run: bun install
      - run: make build-rust-wasm
      - run: make test-rust-wasm

  rust-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - run: make build-rust
      - run: make benchmark-rust

  lint-js:
    runs-on: ubuntu-latest

    steps:
      - name: Use `node` v19
        uses: actions/setup-node@v3
        with:
          node-version: 19
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: make lint-js
